# This file is used to configure the Release Drafter GitHub Action
# https://github.com/marketplace/actions/release-drafter

name-template: 'easydiffraction $RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: 'Added'
    labels:
      - '[scope] significant'
      - '[scope] enhancement'
  - title: 'Fixed'
    labels:
      - '[scope] bug'
  - title: 'Changed'
    labels:
      - '[scope] maintenance'
  - title: 'Documentation'
    labels:
      - '[scope] documentation'

change-template: '- $TITLE (#$NUMBER)'
change-title-escapes: '\<*_&'

version-resolver:
  major:
    labels:
      - '[scope] significant'
  minor:
    labels:
      - '[scope] enhancement'
  patch:
    labels:
      - '[scope] bug'
      - '[scope] maintenance'
  default: patch

# Custom logic for documentation post-releases
# This is a workaround because Release Drafter doesn’t natively support .postN
# We'll append .postN via the version-template below
# - If any merged PR has the [scope] documentation label, the version becomes previous_version.postN.
# - Increment increases for each new .postN release.
# - If no docs label is found, normal SemVer bumping applies.
version-template: >
  {% if prs | selectattr("labels", "contains", "[scope] documentation") | list |
  length > 0 %}
    {{ previous_tag | replace("v","") }}.post{{ increment }}
  {% else %}
    $RESOLVED_VERSION
  {% endif %}

template: |
  $CHANGES
