default_branch: master
develop_branch: develop

cards:
  - group: Tests
    type: gh_action
    title: Code/package tests (GitHub.com)
    file: test-code.yaml
    enabled: true

  - group: Tests
    type: gh_action
    title: Tutorial tests (GitHub.com)
    file: test-tutorials.yaml
    enabled: true

  - group: Tests
    type: gh_action
    title: Package tests (PyPI.org)
    file: test-package-pypi.yaml
    enabled: true

  - group: Code Quality
    type: codefactor
    title: Code quality (CodeFactor.io)
    enabled: true

  - group: Code Quality
    type: radon_mi
    title: Maintainability index (radon)
    report: reports/{branch}/maintainability-index.json
    enabled: true

  - group: Code Quality
    type: radon_cc
    title: Cyclomatic complexity (radon)
    report: reports/{branch}/cyclomatic-complexity.json
    enabled: true

  - group: Size
    type: radon_loc
    title: Source/Logical lines of code (radon)
    report: reports/{branch}/raw-metrics.json
    enabled: true

  - group: Size
    type: radon_ff
    title: Functions/Files count (radon)
    report: reports/{branch}/cyclomatic-complexity.json
    enabled: true

  - group: Coverage
    type: codecov
    title: Unit test coverage (Codecov.io)
    enabled: true

  - group: Coverage
    type: interrogate
    title: Docstring coverage (interrogate)
    report: reports/{branch}/coverage-docstring.txt
    enabled: true

  - group: Build & Release
    type: gh_action
    title: Publishing (PyPI.org)
    workflow: publish-pypi.yml
    enabled: true

  - group: Build & Release
    type: gh_action
    title: Docs build/deployment
    workflow: build-docs.yml
    enabled: true
