default_branch: master
develop_branch: develop

cards:
  - group: Tests
    type: gh_action
    title: Test code and package
    file: test-code.yaml
    enabled: true

  - group: Tests
    type: gh_action
    title: Test tutorials
    file: test-tutorials.yaml
    enabled: true

  - group: Tests
    type: gh_action
    title: Test package (PyPI.org)
    file: test-package-pypi.yaml
    enabled: true

  - group: Code Quality
    type: codefactor
    title: Code quality (CodeFactor.io)
    enabled: true

  - group: Code Quality
    type: radon_mi
    title: Maintainability index (radon)
    report: reports/{branch}/maintainability-index.json
    enabled: true

  - group: Code Quality
    type: radon_cc
    title: Cyclomatic complexity (radon)
    report: reports/{branch}/cyclomatic-complexity.json
    enabled: true

  - group: Size
    type: radon_loc
    title: Source/Logical lines of code
    report: reports/{branch}/raw-metrics.json
    enabled: true

  - group: Size
    type: radon_files
    title: Number of files
    report: reports/{branch}/cyclomatic-complexity.json
    enabled: true

  - group: Size
    type: radon_funcs
    title: Number of functions
    dir: reports/{branch}/cyclomatic-complexity.json
    enabled: true

  - group: Coverage
    type: codecov
    title: Unit test coverage (Codecov.io)
    enabled: true

  - group: Coverage
    type: interrogate
    title: Docstring coverage (interrogate)
    report: reports/{branch}/coverage-docstring.txt
    enabled: true

  - group: Security
    type: gh_action
    title: Scan security
    workflow: scan-security.yaml
    enabled: true

  - group: Build & Release
    type: gh_action
    title: Publish (PyPI.org)
    workflow: publish-pypi.yaml
    enabled: true
