[workspace]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]

##########
# FEATURES
##########

[dependencies] # = [feature.default.dependencies]
libcblas = "*"

[feature.py311.dependencies]
python = "3.11.*"

[feature.py312.dependencies]
python = "3.12.*"

[feature.py313.dependencies]
python = "3.13.*"

##############
# ENVIRONMENTS
##############

[environments]

py311-wheel = { features = ["py311"] } # = ["default", "py311"]
py312-wheel = { features = ["py312"] } # = ["default", "py312"]
py313-wheel = { features = ["py313"] } # = ["default", "py313"]

#######
# TASKS
#######

[tasks]

unit-tests = "python -m pytest --pyargs easydiffraction.tests.unit_tests --color=yes -v"
func-tests = "python -m pytest --pyargs easydiffraction.tests.functional_tests --color=yes -n auto -v"
