[activation.env]
PYTHONIOENCODING = "utf-8"
# The following is needed to resolve issues installing the main package
# from a local path in editable mode in the default environment. With src/
# included in PYTHONPATH, we use the source code directly in the first place,
# instead of the installed package.
PYTHONPATH = "$(pwd)/src${PYTHONPATH:+:$PYTHONPATH}"

[workspace]
# Platforms supported for the lock file (pixi.lock)
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]

# Channels used to fetch packages
channels = ["conda-forge"]

##########
# FEATURES
##########

# Default feature configuration

[dependencies] # == [feature.default.dependencies]
pip = "*"        # Required to install from PyPI
jupyterlab = "*" # JupyterLab for notebooks
#pypi-dependencies = { file = "pyproject.toml", extras = ["dev"] }

[target.win-64.dependencies]
libcblas = "*" # CBLAS library for linear algebra. Required for pdffit2.

[pypi-dependencies] # == [feature.default.pypi-dependencies]
pixi-kernel = "*" # Pixi Jupyter kernel
#easydiffraction = { version = "*", extras = ["all"] } # Main package
easydiffraction = { path = ".", extras = ["all"] } # Main package

# Extra features for different Python versions

# These features specify the Python version for the environment.
# Each feature corresponds to a specific Python version.

[feature.py311.dependencies]
python = "3.11.*"

[feature.py313.dependencies]
python = "3.13.*"

# This feature installs Node.js and Prettier for formatting
# non-Python files.

[feature.nodejs.dependencies]
nodejs = ">=20,<21" # Required for prettier; pinned to a stable LTS

##############
# ENVIRONMENTS
##############

[environments]

# The `default` environment is always included in the lock file, so it does not
# need to be specified explicitly in the environments section.

default = { features = ["py313", "nodejs"] }

py311-dev = { features = ["py311", "nodejs"] }
py313-dev = { features = ["py313", "nodejs"] }

#######
# TASKS
#######

[tasks]

# 🧪 Testing Tasks
unit-tests = "python -m pytest tests/unit/ --color=yes -v"
func-tests = "python -m pytest tests/functional/ --color=yes -n auto -v"
notebook-tests = 'python -m pytest --nbmake tutorials/ --nbmake-timeout=600 --color=yes -n auto -v'
script-tests = 'python -m pytest tools/test_scripts.py --color=yes -n auto -v'

tests = { depends-on = ["unit-tests", "func-tests"] }

# 🧹 Code Quality

## ✔️ Checks
pyproject-check = "python -m validate_pyproject pyproject.toml"
py-lint-check = "python -m ruff check ."
py-format-check = "python -m ruff format . --check"
nonpy-format-check = "npx prettier . --list-different --config=prettierrc.toml"
nonpy-format-check-modified = "npx prettier $(git diff --name-only HEAD | grep -E '\\.(json|ya?ml|toml|md|css|html)$' || echo .) --list-different --config=prettierrc.toml"
notebook-format-check = 'nbqa ruff tutorials/'
docs-format-check = "docformatter --check src/ tutorials/"
block-pixi-sha256 = "python tools/block-pixi-sha256.py"

## 🛠️ Fixes
py-lint-fix = "python -m ruff check . --fix"
py-format-fix = "python -m ruff format ."
nonpy-format-fix = "npx prettier . --list-different --write --config=prettierrc.toml"
nonpy-format-fix-modified = "npx prettier $(git diff --name-only HEAD | grep -E '\\.(json|ya?ml|toml|md|css|html)$' || echo .) --list-different --write --config=prettierrc.toml"
notebook-format-fix = 'nbqa ruff tutorials/ --fix'
docs-format-fix = "docformatter --in-place src/ tutorials/"

fix = { depends-on = [
  "py-format-fix",
  "docs-format-fix",
  "py-lint-fix",
  "nonpy-format-fix-modified",
] }

# 🧮 Code Complexity
complexity-check = "radon cc -s src/"
complexity-check-json = "radon cc -s -j src/"
maintainability-check = "radon mi src/"
maintainability-check-json = "radon mi -j src/"
raw-metrics = "radon raw -s src/"
raw-metrics-json = "radon raw -s -j src/"

# 📊 Coverage
unit-tests-coverage = "pixi run unit-tests --cov=src/easydiffraction --cov-report=term-missing"
func-tests-coverage = "pixi run func-tests --cov=src/easydiffraction --cov-report=term-missing"
docstring-coverage = "interrogate -c pyproject.toml src/"

coverage = "pixi run docstring-coverage || true; pixi run unit-tests-coverage || true"

# 📓 Notebook Management
notebook-convert = 'jupytext tutorials/*.py --from py:percent --to ipynb'
notebook-strip = 'nbstripout tutorials/*.ipynb'
notebook-tweak = 'python tools/tweak_notebooks.py tutorials/'
notebook-clean = 'rm -f tutorials/*.ipynb'
notebook-exec = 'python -m pytest --nbmake tutorials/ --nbmake-timeout=600 --overwrite --color=yes -n auto -v'

notebook-prepare = { depends-on = [
  "notebook-convert",
  "notebook-strip",
  "notebook-tweak",
] }

# 📚 Documentation Tasks
docs-assets = "tools/add_assets_to_docs.sh"
docs-notebooks = "mv tutorials/*.ipynb docs/tutorials/"
docs-config = "python tools/create_mkdocs_yml.py"
docs-serve = 'JUPYTER_PLATFORM_DIRS=1 PYTHONWARNINGS="ignore::RuntimeWarning" python -m mkdocs serve --dirty'
docs-build = 'JUPYTER_PLATFORM_DIRS=1 PYTHONWARNINGS="ignore::RuntimeWarning" python -m mkdocs build'
docs-clean = "tools/cleanup_docs.sh"
docs-setup = { depends-on = [
  "docs-config",
  "docs-assets",
  "notebook-prepare",
  "docs-notebooks",
] }

# 🚀 Development & Build Tasks
dist-build = "python -m build --wheel --outdir dist"
spdx-update = "python tools/update_spdx.py"
prettier-install = "npm install --no-save --no-audit --no-fund prettier prettier-plugin-toml"
pre-commit-install = "pre-commit clean && pre-commit install --hook-type pre-commit --hook-type pre-push --overwrite"
pre-commit-update = "pre-commit autoupdate"
pre-commit = "pre-commit run --all-files --hook-stage pre-commit"
pre-push = "pre-commit run --all-files --hook-stage pre-push"

# 🔗 Shortcuts
easydiffraction = "python -m easydiffraction"
tutorials-list = "python -m easydiffraction list-tutorials"
tutorials-fetch = "python -m easydiffraction fetch-tutorials"
