"""
Bump or verify the vendored JavaScript runtimes.

Fetches the pinned Plotly and Three.js assets from jsDelivr with
integrity checks, writes them into their canonical vendor folders, and
regenerates each folder's ``LICENSES.md``. With ``--check`` it re-hashes
the already-vendored files against the pinned table and writes nothing
(a CI drift guard); no network access is used in that mode.

The pinned table below is the single source of truth for the vendored
runtime versions. To bump a runtime: change its ``version``, the asset
URLs, and the expected ``sha256`` hashes, then run
``pixi run vendor-update-js``.
"""

from __future__ import annotations

import argparse
import hashlib
import shutil
import sys
from dataclasses import dataclass
from pathlib import Path

import pooch

_REPO_ROOT = Path(__file__).resolve().parent.parent
_CACHE_DIR = Path.home() / '.cache' / 'easydiffraction-vendored-js'


@dataclass(frozen=True)
class VendoredAsset:
    """One vendored file: its name, source URL, and expected hash."""

    filename: str
    url: str
    sha256: str


@dataclass(frozen=True)
class VendoredRuntime:
    """A pinned runtime vendored as one or more files in one folder."""

    name: str
    package: str
    version: str
    dest_dir: Path
    licence: str
    assets: tuple[VendoredAsset, ...]


THREEJS = VendoredRuntime(
    name='Three.js',
    package='three',
    version='0.160.0',
    dest_dir=Path('src/easydiffraction/display/structure/renderers/vendor/threejs'),
    licence=(
        'MIT — Copyright © 2010-2024 three.js authors. '
        'See `https://github.com/mrdoob/three.js/blob/dev/LICENSE`.'
    ),
    assets=(
        VendoredAsset(
            'three.module.js',
            'https://cdn.jsdelivr.net/npm/three@0.160.0/build/three.module.js',
            '76dea8151bc9352aef3528b4262e249b2604f62543828328db978d060d61a495',
        ),
        VendoredAsset(
            'OrbitControls.js',
            'https://cdn.jsdelivr.net/npm/three@0.160.0/examples/jsm/controls/OrbitControls.js',
            '5a44a9e86a2a0fb11933eed69bc2cd33c76a496854c1aed6ed776efa87d7b064',
        ),
        VendoredAsset(
            'CSS2DRenderer.js',
            'https://cdn.jsdelivr.net/npm/three@0.160.0/examples/jsm/renderers/CSS2DRenderer.js',
            'a4f0f79184c043f6b9d2654d8ba051e49a7d631d34e8f437c1804798a68c379f',
        ),
    ),
)

PLOTLY = VendoredRuntime(
    name='Plotly.js (cartesian bundle)',
    package='plotly.js',
    version='3.5.0',
    dest_dir=Path('docs/docs/assets/javascripts/vendor/plotly'),
    licence=(
        'MIT — Copyright 2012-2026 Plotly, Inc. '
        'See `https://github.com/plotly/plotly.js/blob/master/LICENSE`.'
    ),
    assets=(
        VendoredAsset(
            'plotly-cartesian.min.js',
            'https://cdn.jsdelivr.net/npm/plotly.js@3.5.0/dist/plotly-cartesian.min.js',
            '65248e65cd56530272d19ff7ef12cb849228f4464001f3f67cbb2b95adb22443',
        ),
    ),
)

RUNTIMES: tuple[VendoredRuntime, ...] = (THREEJS, PLOTLY)


def _sha256(path: Path) -> str:
    """
    Return the SHA-256 hex digest of a file.

    Parameters
    ----------
    path : Path
        File to hash.

    Returns
    -------
    str
        The hex digest.
    """
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _license_text(runtime: VendoredRuntime) -> str:
    """
    Render the ``LICENSES.md`` content for a vendored runtime.

    Parameters
    ----------
    runtime : VendoredRuntime
        The runtime whose vendored files to document.

    Returns
    -------
    str
        The full markdown content.
    """
    rows = '\n'.join(f'| `{asset.filename}` | `{asset.url}` |' for asset in runtime.assets)
    return (
        f'# Vendored {runtime.name}\n\n'
        f'Pinned, bundled snapshot fetched verbatim from jsDelivr '
        f'(npm `{runtime.package}@{runtime.version}`). Generated by '
        f'`tools/bump_vendored_js.py`; do not edit by hand — replace only '
        f'by re-fetching the pinned version with `pixi run vendor-update-js`.\n\n'
        f'| File | Source URL |\n| --- | --- |\n{rows}\n\n'
        f'**Version:** {runtime.version}.\n\n'
        f'**Licence:** {runtime.licence}\n\n'
        f'These are upstream snapshots, not project-owned code: they are '
        f'excluded from linting, formatting, coverage, and test-structure '
        f'mirroring in `pyproject.toml`.\n'
    )


def _bump_runtime(runtime: VendoredRuntime) -> None:
    """
    Fetch a runtime's assets and regenerate its ``LICENSES.md``.

    Parameters
    ----------
    runtime : VendoredRuntime
        The runtime to fetch and write.
    """
    dest_dir = _REPO_ROOT / runtime.dest_dir
    dest_dir.mkdir(parents=True, exist_ok=True)
    for asset in runtime.assets:
        fetched = pooch.retrieve(
            url=asset.url,
            known_hash=f'sha256:{asset.sha256}',
            fname=asset.filename,
            path=_CACHE_DIR,
        )
        shutil.copy2(fetched, dest_dir / asset.filename)
        print(f'  wrote {runtime.dest_dir / asset.filename}')
    (dest_dir / 'LICENSES.md').write_text(_license_text(runtime), encoding='utf-8')
    print(f'  wrote {runtime.dest_dir / "LICENSES.md"}')


def _check_runtime(runtime: VendoredRuntime) -> list[str]:
    """
    Return drift messages for a runtime's vendored files.

    Parameters
    ----------
    runtime : VendoredRuntime
        The runtime to verify.

    Returns
    -------
    list[str]
        One message per missing or mismatched file; empty when clean.
    """
    problems: list[str] = []
    dest_dir = _REPO_ROOT / runtime.dest_dir
    for asset in runtime.assets:
        path = dest_dir / asset.filename
        if not path.is_file():
            problems.append(f'missing: {runtime.dest_dir / asset.filename}')
            continue
        actual = _sha256(path)
        if actual != asset.sha256:
            problems.append(
                f'hash drift: {runtime.dest_dir / asset.filename} '
                f'(expected {asset.sha256}, actual {actual})'
            )
    return problems


def bump() -> int:
    """
    Fetch and write every pinned runtime.

    Returns
    -------
    int
        Process exit code (always ``0``; integrity failures raise).
    """
    for runtime in RUNTIMES:
        print(f'{runtime.name} {runtime.version}:')
        _bump_runtime(runtime)
    print('Done. Stage and commit the refreshed vendored files.')
    return 0


def check() -> int:
    """
    Verify vendored files match the pinned hashes.

    Returns
    -------
    int
        ``0`` when every file matches, ``1`` on any drift.
    """
    problems: list[str] = []
    for runtime in RUNTIMES:
        problems.extend(_check_runtime(runtime))
    if problems:
        print('Vendored JS drift detected:')
        for problem in problems:
            print(f'  {problem}')
        return 1
    print('Vendored JS matches the pinned table.')
    return 0


def main() -> int:
    """
    Parse arguments and run the bump or check workflow.

    Returns
    -------
    int
        Process exit code.
    """
    parser = argparse.ArgumentParser(description='Bump or verify vendored JS runtimes.')
    parser.add_argument(
        '--check',
        action='store_true',
        help='Verify vendored files against the pinned hashes (no network, no writes).',
    )
    args = parser.parse_args()
    return check() if args.check else bump()


if __name__ == '__main__':
    sys.exit(main())
