###########################
# Override default settings
###########################

# Project information
site_name: EasyDiffraction Library
site_url: https://docs.easydiffraction.org/lib

# Repository
repo_url: https://github.com/easyscience/diffraction-lib
edit_uri: edit/develop/docs/

# Copyright
copyright: © 2025 EasyDiffraction

# Extra icons in the bottom right corner
extra:
  social:
    - icon: easydiffraction  # File: overrides/.icons/easydiffraction.svg
      link: https://easydiffraction.org
    - icon: fontawesome/brands/github  # Name as in Font Awesome
      link: https://github.com/easyscience/diffraction-lib

# Jupyter notebooks
plugins:
  - mkdocs-jupyter:
      execute_ignore:
        - '*.ipynb'  # Ignore quick notebooks from execution
#        - '*emcee*.ipynb' # Ignore notebooks with 'emcee' in the name from execution

##################
# Add new settings
##################

# Exclude files and folders from the global navigation
not_in_nav: |
  index.md
  user-guide/parameters

# Format and layout of the global navigation for the site
nav:
  - Introduction:
      - Introduction: introduction/index.md
  - Installation & Setup:
      - Installation & Setup: installation-and-setup/index.md
  - User Guide:
      - User Guide: user-guide/index.md
      - Glossary: user-guide/glossary.md
      - Concept: user-guide/concept.md
      - Data Format: user-guide/data-format.md
      - Parameters: user-guide/parameters.md
      - First Steps: user-guide/first-steps.md
      - Analysis Workflow:
        - Analysis Workflow: user-guide/analysis-workflow/index.md
        - Project: user-guide/analysis-workflow/project.md
        - Sample Model: user-guide/analysis-workflow/model.md
        - Experiment: user-guide/analysis-workflow/experiment.md
        - Analysis: user-guide/analysis-workflow/analysis.md
        - Summary: user-guide/analysis-workflow/summary.md
  - Tutorials:
      - Tutorials: tutorials/index.md
      - Getting Started:
          - LBCO quick: tutorials/quick_single-fit_pd-neut-cwl_LBCO-HRPT.ipynb
          - LBCO basic: tutorials/basic_single-fit_pd-neut-cwl_LBCO-HRPT.ipynb
          - PbSO4 advanced: tutorials/advanced_joint-fit_pd-neut-xray-cwl_PbSO4.ipynb
      - Structure Refinement:
          - Co2SiO4 pd-neut-cwl: tutorials/cryst-struct_pd-neut-cwl_CoSiO4-D20.ipynb
          - HS pd-neut-cwl: tutorials/cryst-struct_pd-neut-cwl_HS-HRPT.ipynb
          - Si pd-neut-tof: tutorials/cryst-struct_pd-neut-tof_Si-SEPD.ipynb
          - NCAF pd-neut-tof: tutorials/cryst-struct_pd-neut-tof_NCAF-WISH.ipynb
      - Pair Distribution Function:
          - Ni pd-neut-cwl: tutorials/pdf_pd-neut-cwl_Ni.ipynb
          - Si pd-neut-tof: tutorials/pdf_pd-neut-tof_Si-NOMAD.ipynb
          - NaCl pd-xray: tutorials/pdf_pd-xray_NaCl.ipynb
  - API Reference:
      - API Reference: api-reference/index.md
      - api-reference/core.md
      - api-reference/crystallography.md
      - api-reference/utils.md
      - api-reference/plotting.md
      - api-reference/sample_models.md
      - api-reference/experiments.md
      - api-reference/analysis.md
