###########################
# Override default settings
###########################

# Project information
site_name: EasyDiffraction Library
site_url: https://docs.easydiffraction.org/lib

# Repository
repo_url: https://github.com/easyscience/diffraction-lib
edit_uri: edit/develop/docs/

# Copyright
copyright: © 2025 EasyDiffraction

# Extra icons in the bottom right corner
extra:
  social:
    - icon: easydiffraction  # File: overrides/.icons/easydiffraction.svg
      link: https://easydiffraction.org
    - icon: fontawesome/brands/github  # Name as in Font Awesome
      link: https://github.com/easyscience/diffraction-lib

# Jupyter notebooks
plugins:
  - mkdocs-jupyter:
      execute_ignore:
#        - '*emcee*.ipynb' # Ignore notebooks with 'emcee' in the name from execution

##################
# Add new settings
##################

# Exclude files and folders from the global navigation
not_in_nav: |
  index.md
  usage/parameters

# Format and layout of the global navigation for the site
nav:
  - Introduction:
      - Introduction: introduction/index.md
  - Installation & Setup:
      - Installation & Setup: installation/index.md
  - User Guide:
      - User Guide: usage/index.md
      - Glossary: usage/glossary.md
      - Concept: usage/concept.md
      - Data Format: usage/data-format.md
      - Parameters: usage/parameters.md
      - Getting Started: usage/getting-started.md
      - Workflow Steps:
        - Workflow Steps: usage/workflow-steps/index.md
        - Project: usage/workflow-steps/project.md
        - Sample Model: usage/workflow-steps/model.md
        - Experiment: usage/workflow-steps/experiment.md
        - Analysis: usage/workflow-steps/analysis.md
        - Summary: usage/workflow-steps/summary.md
  - Tutorials:
      - Tutorials: tutorials/index.md
      - Getting Started:
          - LBCO quick: tutorials/quick_single-fit_pd-neut-cwl_LBCO-HRPT.ipynb
          - LBCO basic: tutorials/basic_single-fit_pd-neut-cwl_LBCO-HRPT.ipynb
          - PbSO4 advanced: tutorials/advanced_joint-fit_pd-neut-xray-cwl_PbSO4.ipynb
      - Structure Refinement:
          - Co2SiO4 pd-neut-cwl: tutorials/cryst-struct_pd-neut-cwl_CoSiO4-D20.ipynb
          - HS pd-neut-cwl: tutorials/cryst-struct_pd-neut-cwl_HS-HRPT.ipynb
          - Si pd-neut-tof: tutorials/cryst-struct_pd-neut-tof_Si-SEPD.ipynb
          - NCAF pd-neut-tof: tutorials/cryst-struct_pd-neut-tof_NCAF-WISH.ipynb
      - Pair Distribution Function:
          - Ni pd-neut-cwl: tutorials/pdf_pd-neut-cwl_Ni.ipynb
          - Si pd-neut-tof: tutorials/pdf_pd-neut-tof_Si-NOMAD.ipynb
          - NaCl pd-xray: tutorials/pdf_pd-xray_NaCl.ipynb
  - API Reference:
      - API Reference: api/index.md
      - api/core.md
      - api/crystallography.md
      - api/utils.md
      - api/plotting.md
      - api/sample_models.md
      - api/experiments.md
      - api/analysis.md
