name: Branch Badge Summary

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  CI_BRANCH: ${{ github.head_ref || github.ref_name }}

jobs:
  make-badges:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up pixi
        uses: prefix-dev/setup-pixi@v0.9.0
        with:
          environments: >-
            py313-dev
          activate-environment: py313-dev
          run-install: true
          frozen: true
          cache: false
          post-cleanup: false

      - name: Run docstring coverage and code complexity (master branch)
        run: |
          git worktree add ../worktree-master origin/master
          cp -f pixi.toml ../worktree-master/
          cp -rf tools ../worktree-master/
          cd ../worktree-master
          pixi run --manifest-path {{ env.PIXI_PROJECT_MANIFEST }} docstring-coverage > ../coverage-docstring-master.txt
          pixi run --manifest-path {{ env.PIXI_PROJECT_MANIFEST }} complexity-check-json > ../cyclomatic-complexity-master.json
          pixi run --manifest-path {{ env.PIXI_PROJECT_MANIFEST }} maintainability-check-json > ../maintainability-index-master.json

      - name: Run docstring coverage and code complexity (develop branch)
        run: |
          git worktree add ../worktree-develop origin/develop
          cp -f pixi.toml ../worktree-develop/
          cp -rf tools ../worktree-develop/
          cd ../worktree-develop
          pixi run --manifest-path {{ env.PIXI_PROJECT_MANIFEST }} docstring-coverage > ../coverage-docstring-develop.txt
          pixi run --manifest-path {{ env.PIXI_PROJECT_MANIFEST }} complexity-check-json > ../cyclomatic-complexity-develop.json
          pixi run --manifest-path {{ env.PIXI_PROJECT_MANIFEST }} maintainability-check-json > ../maintainability-index-develop.json

      - name: Run docstring coverage and code complexity (feature branch)
        run: |
          git worktree add ../worktree-feature $CI_BRANCH
          cp -f pixi.toml ../worktree-feature/
          cp -rf tools ../worktree-feature/
          cd ../worktree-feature
          pixi run --manifest-path {{ env.PIXI_PROJECT_MANIFEST }} docstring-coverage > ../coverage-docstring-feature.txt
          pixi run --manifest-path {{ env.PIXI_PROJECT_MANIFEST }} complexity-check-json > ../cyclomatic-complexity-feature.json
          pixi run --manifest-path {{ env.PIXI_PROJECT_MANIFEST }} maintainability-check-json > ../maintainability-index-feature.json

      - name: Generate badge summary markdown
        run: >
          pixi run make-badges 
          --output BADGES.md 
          --branch $CI_BRANCH
          --coverage-docstring-master coverage-docstring-master.txt
          --coverage-docstring-develop coverage-docstring-develop.txt
          --coverage-docstring-feature coverage-docstring-feature.txt
          --cyclomatic-complexity-master cyclomatic-complexity-master.json
          --cyclomatic-complexity-develop cyclomatic-complexity-develop.json
          --cyclomatic-complexity-feature cyclomatic-complexity-feature.json
          --maintainability-index-master maintainability-index-master.json
          --maintainability-index-develop maintainability-index-develop.json
          --maintainability-index-feature maintainability-index-feature.json

      - name: Append badge summary to step summary
        run: cat BADGES.md >> $GITHUB_STEP_SUMMARY
