name: Test unpinned package from PyPI

on:
  # Run daily, at 00:00.
  schedule:
    - cron: '0 0 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Allow only one concurrent workflow, skipping runs queued between the run
# in-progress and latest queued. And cancel in-progress runs.
concurrency:
  group:
    ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test-package:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Set up pixi
        uses: prefix-dev/setup-pixi@v0.9.0
        with:
          run-install: false
          cache: false
          post-cleanup: false

      - name: Initialize a new Pixi project for EasyDiffraction
        run: pixi init

      - name: Add Conda dependencies
        run: pixi add python==3.13 libcblas

      - name: Add PyPI dependencies
        run: pixi add --pypi "easydiffraction[dev,visualization]"

      - name: Run tests to verify the installation
        run: pixi run python -m pytest --pyargs easydiffraction.tests
