name: Tutorial tests on Colab

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Allow only one concurrent workflow, skipping runs queued between the run in-progress and latest queued.
# And cancel in-progress runs.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  tutorial-tests-colab:
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.12']

    runs-on: ubuntu-latest

    container:
      image: europe-docker.pkg.dev/colab-images/public/runtime:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
